import { z } from "zod";

// --- Moneda ---
export const MonedaSchema = z.object({
    moneda_id: z.string().optional(), // Optional on create if generated by backend/db, but usually required for updates
    moneda_nombre: z.string().min(1, "Nombre es requerido"),
    codigo: z.string().min(1, "Código es requerido"),
    simbolo: z.string().optional(),
    // imagen: z.any().optional(), // Bytes handling might need special care, skipping for basic CRUD for now or using base64 string
    is_deleted: z.boolean().optional(),
    version: z.number().optional(),
});

export const CreateMonedaSchema = MonedaSchema.omit({ moneda_id: true, is_deleted: true, version: true });
export const UpdateMonedaSchema = MonedaSchema.partial();

// --- Nacionalidad ---
export const NacionalidadSchema = z.object({
    nacionalidad_id: z.string().optional(),
    nacionalidad_nombre: z.string().min(1, "Nombre es requerido"),
    codigo_iso: z.string().min(1, "Código ISO es requerido"),
    // bandera: z.any().optional(),
    is_deleted: z.boolean().optional(),
    version: z.number().optional(),
});

export const CreateNacionalidadSchema = NacionalidadSchema.omit({ nacionalidad_id: true, is_deleted: true, version: true });
export const UpdateNacionalidadSchema = NacionalidadSchema.partial();

// --- TipoPago ---
export const TipoPagoSchema = z.object({
    tipo_pago_id: z.string().optional(),
    nombre_tipo_pago: z.string().min(1, "Nombre es requerido"),
    is_deleted: z.boolean().optional(),
    version: z.number().optional(),
});

export const CreateTipoPagoSchema = TipoPagoSchema.omit({ tipo_pago_id: true, is_deleted: true, version: true });
export const UpdateTipoPagoSchema = TipoPagoSchema.partial();

// --- TipoCambio ---
export const TipoCambioSchema = z.object({
    tipo_cambio_id: z.string().optional(),
    moneda_id_base: z.string().min(1, "Moneda Base es requerida"),
    moneda_id_target: z.string().min(1, "Moneda Target es requerida"),
    exchange_rate: z.number().min(0, "Tasa de cambio debe ser positiva"),
    fecha_inicio: z.string().or(z.date()).transform((val) => new Date(val)),
    fecha_expiracion: z.string().or(z.date()).optional().nullable().transform((val) => val ? new Date(val) : null),
    activo: z.boolean().optional(),
    is_deleted: z.boolean().optional(),
    version: z.number().optional(),
});

export const CreateTipoCambioSchema = TipoCambioSchema.omit({ tipo_cambio_id: true, is_deleted: true, version: true });
export const UpdateTipoCambioSchema = TipoCambioSchema.partial();

// --- Referencia ---
export const ReferenciaSchema = z.object({
    referencia_id: z.string().optional(),
    nombre_referencia: z.string().min(1, "Nombre es requerido"),
    is_deleted: z.boolean().optional(),
    version: z.number().optional(),
});

export const CreateReferenciaSchema = ReferenciaSchema.omit({ referencia_id: true, is_deleted: true, version: true });
export const UpdateReferenciaSchema = ReferenciaSchema.partial();

// --- Horario ---
export const HorarioSchema = z.object({
    horario_id: z.string().optional(),
    nombre_horario: z.string().min(1, "Nombre es requerido"),
    hora_inicio: z.number().int().min(0).max(23),
    hora_fin: z.number().int().min(0).max(23),
    is_deleted: z.boolean().optional(),
    version: z.number().optional(),
});

export const CreateHorarioSchema = HorarioSchema.omit({ horario_id: true, is_deleted: true, version: true });
export const UpdateHorarioSchema = HorarioSchema.partial();

// --- PlanesPago ---
export const PlanesPagoSchema = z.object({
    id_planes_pago: z.string().optional(),
    nombre_plan_pago: z.string().optional().nullable(),
    importe_plan_pago: z.number().min(0),
    duracion_plan_pago: z.number().int().min(1),
    activo: z.boolean().optional(),
    moneda_id: z.string().min(1, "Moneda es requerida"),
    is_deleted: z.boolean().optional(),
    version: z.number().optional(),
});

export const CreatePlanesPagoSchema = PlanesPagoSchema.omit({ id_planes_pago: true, is_deleted: true, version: true });
export const UpdatePlanesPagoSchema = PlanesPagoSchema.partial();

// --- Cuenta ---
export const CuentaSchema = z.object({
    cuenta_id: z.string().optional(),
    nombre_cuenta: z.string().min(1, "Nombre es requerido"),
    moneda_id: z.string().min(1, "Moneda es requerida"),
    is_deleted: z.boolean().optional(),
    version: z.number().optional(),
});

export const CreateCuentaSchema = CuentaSchema.omit({ cuenta_id: true, is_deleted: true, version: true });
export const UpdateCuentaSchema = CuentaSchema.partial();
